language: rust
sudo: false
cache:
- apt
- cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
notifications:
  slack:
    rooms:
      secure: A07vX/imdnduYiZt1q7VS2Y69MFKWVOZusHpUtwlzru68UIGN9PhtkmZCaN7+QN5tmJ0WVG6s5SEGuBk7iwzRCojdV9wn9Lj2DAW2F0rqyAzXGV+HtVdFQWPsQnneESxcZft5ItSTN9UPvgwiT6zgr0WMa2pqmR5IjePtoNNBrEXtgOvdjWKlV863D80q2U5ptaMUc5nuFrJNKCaWvj+l8W8918Bs4MrB8eG3DhQ5bPfqZ4EP8LJpYd0BszHeYuFw1geF5nNiO4zhKFBCf3V0oS/SEpNDe2VW5j2aZ0yKJFfnxID3dXPihbcIi/J0irvvURUAAGTF2pDvFfmppMOTXskBU263Tr2f3R3H/IFLoqvcuGEdFD8nS8NW+sWyc9FlOm9O5Uf352JhTrRwlGXA7bjo5lB+GuGEbofzOT/phHJwA2FgCvB/LH23B8J+hzV3P+zbFcKoTXhZhILTYdGH3cw8aic3w8s47mAH+bbNrMRs1wrRuzF6c2+aTM4bVtl2lYVpfPoLspH8BOzXDtbijAkwehtMpBzu4gQwmvylItlzM63s++mSly96dU8gUrXBKx1rWq85uiNouTk/qFz+k5gMVxe3k3eHytlvdPjx2bbhu7ajk74A6NRzqyK4AKIEqeEWSFdiENmhtfZscHWOzMU3C4jjILdBvhJnOjwyHE=
