# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name            = "eventor"
version         = "0.1.11"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
keywords        = ["subsystem", "event"]
description     = "Event library"
readme          = "README.md"
documentation   = "https://github.com/hanepjiv/eventor-rs/wiki"
homepage        = "https://github.com/hanepjiv/eventor-rs"
repository      = "https://github.com/hanepjiv/eventor-rs.git"
# =============================================================================
[dependencies]
libc            = { version = "^0.2.18", default-features = false }
# -----------------------------------------------------------------------------
elicit         = { git = "https://github.com/hanepjiv/elicit-rs.git", default-features = false }
#elicit           = { path = "../../elicit-rs/orig", default-features = false }
hash_combine   = { git = "https://github.com/hanepjiv/hash_combine-rs.git", default-features = false }
#hash_combine     = { path = "../../hash_combine-rs/orig", default-features = false }
