# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name            = "eventor"
version         = "0.1.11"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
keywords        = ["subsystem", "event"]
description     = "Event library"
readme          = "README.md"
documentation   = "https://github.com/hanepjiv/eventor-rs/wiki"
homepage        = "https://github.com/hanepjiv/eventor-rs"
repository      = "https://github.com/hanepjiv/eventor-rs.git"
# =============================================================================
[dependencies]
libc            = "^0.2.17"
log             = "^0.3.6"
# -----------------------------------------------------------------------------
elicit          = { git = "https://github.com/hanepjiv/elicit-rs.git" }
#elicit          = { path = "../../elicit-rs/orig" }
hash_combine    = { git = "https://github.com/hanepjiv/hash_combine-rs.git" }
#hash_combine    = { path = "../../hash_combine-rs/orig" }
