# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
edition                 = "2021"
name                    = "eventor"
version                 = "0.7.0"
authors                 = ["hanepjiv <hanepjiv@gmail.com>"]
license                 = "MIT OR Apache-2.0"
keywords                = ["subsystem", "event"]
description             = "Event library"
readme                  = "README.md"
documentation           = "https://github.com/hanepjiv/eventor-rs/wiki"
homepage                = "https://github.com/hanepjiv/eventor-rs"
repository              = "https://github.com/hanepjiv/eventor-rs.git"
publish                 = true
# =============================================================================
[dependencies]
libc                    = { default-features = false, version = "^0.2" }
log                     = { default-features = false, version = "^0.4" }
hash_combine            = { default-features = false, version = "^0.3" }
# -----------------------------------------------------------------------------
[dependencies.elicit]
default-features        = false
version                 = "^0.8"
#path                    = "../../elicit-rs/orig"
