[package]
name            = "eventor"
version         = "0.1.3"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]

[dependencies]
libc            = "^0.2.10"
log             = "^0.3.6"
# ------------------------------------------------------------------------------
elicit          = { git = "https://github.com/hanepjiv/elicit-rs.git" }
hash_combine    = { git = "https://github.com/hanepjiv/hash_combine-rs.git" }
