# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
edition                 = "2021"
name                    = "eventor"
version                 = "0.9.0"
authors                 = ["hanepjiv <hanepjiv@gmail.com>"]
license                 = "MIT OR Apache-2.0"
keywords                = ["subsystem", "event"]
description             = "Event library"
readme                  = "README.md"
documentation           = "https://github.com/hanepjiv/eventor-rs/wiki"
homepage                = "https://github.com/hanepjiv/eventor-rs"
repository              = "https://github.com/hanepjiv/eventor-rs.git"
publish                 = false
# =============================================================================
[dependencies]
hash_combine            = { default-features = false, version = "^0.3" }
log                     = { default-features = false, version = "^0.4" }
uuid                    = { default-features = false, version = "^1" }
# -----------------------------------------------------------------------------
[dependencies.elicit]
default-features        = false
version                 = "^0.10"

#git                     = "ssh://git@github.com/hanepjiv/elicit-rs.git"
#branch                  = "main"

#path                   = "../../elicit-rs/orig"
# =============================================================================
[workspace]
exclude                 = [ "examples/"
                            ]
members                 = [
                            ]
